# -*- coding: utf-8 -*-
"""w1w2_260302.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/122FRZfPdwOnUpvt32SYr30hr4lKAGyd0
"""

import sys
import sklearn
import numpy
import pandas
print("Python version:", sys.version.split()[0])
print("scikit-learn version:", sklearn.__version__)
print("NumPy version:", numpy.__version__)
print("Pandas version:", pandas.__version__)

temperature = 28
if temperature >= 28:
  print("It's too hot.")
elif 24 < temperature < 28:
  print("It's comfortable.")
else:
  print("It's cold.")

a = ["a", "b", "c", "d", "e"]
print(a[-1:-2:-1])

import csv

with open('虎尾實登.csv', newline='', encoding='utf-8') as csvfile:
  rows = csv.reader(csvfile)
  for row in rows:
    print(row)

import pandas as pd
df = pd.read_csv('虎尾實登.csv')
#$ df
print(df.columns)
# df.head(6)
df[['單價元平方公尺']]

from sklearn.datasets import load_wine
from sklearn.datasets import load_wine
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

#Load dataset
wine = load_wine()
df = pd.DataFrame(wine.data,columns=wine.feature_names)
df['target'] = wine.target
df.head()

from sklearn.datasets import load_wine
from sklearn.datasets import load_wine
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

#Load dataset
wine = load_wine()
df = pd.DataFrame(wine.data,columns=wine.feature_names)
df['target'] = wine.target
df.head()

X=df[['alcohol','proline']]
X.head()

y=df['target']
print(type(y))
y.head()

#Train / test split
X_train, X_test, y_train, y_test = train_test_split(
  X, y, test_size=0.25, random_state=4
)
#KNN without i scaling
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
accuracy = knn.score(X_test, y_test)
print("Accuracy:", accuracy)